import React from "react";
export const Undo = () => "undo";
export const Redo = () => "redo";
export const Clear = () => "clear";
export const Blockquote = () => "blockquote";
export const Divider = () => "divider";
export const Code = () => "code";
export const Bold = () => "bold";
export const Del = () => "del";
export const Ul = () => "ul";
export const Ol = () => "ol";
export const LinkIcon = () => "linkicon";
export const PictureIcon = () => "picture";
export const ColorIcon = () => "color";
export const Italic = () => "italic";
export const Underline = () => "underline";
export const Video = () => "video";
